---
title: "Developing Data Products Assignment Week 2"
author: "Bert Haak"
date: "March 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Soccer Stadiums in Rotterdam Netherlands

The map shows the soccer stadiums of the three professional soccer clubs in Rotterdam. The icon is the flag of Rotterdam. The popups are links to the official websites of the clubs.

## Leaflet Map with the Soccer Stadiums

```{r, echo=FALSE}
library(leaflet)
set.seed(2017-03-23)
rdmIcon <- makeIcon(
  iconUrl = "D:/Documents/Coursera/repos/DevDataProdAssgnWk2/flagRot.png",
  iconWidth = 31*215/230, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16
)

soccerSites <- c(
  "<a href='https://www.feyenoord.nl/'>Feyenoord Rotterdam (The Best)</a>",
  "<a href='https://www.sparta-rotterdam.nl/'>Sparta Rotterdam</a>",
  "<a href='http://sbvexcelsior.nl/'>Excelsior Rotterdam</a>"
)

awk2LatLong <- data.frame(
  lat = c(51.8896664413, 51.919485, 51.916944 ),
  lng = c(4.52061625086, 4.433619, 4.520556))

awk2LatLong %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers(icon = rdmIcon, popup = soccerSites)
```